### PR TITLE
🔨 Add http_exception handler to Admin class

### PR DESCRIPTION
**Pull request by agn-7**
Fixed the exception handler to bring a template for the errors using an awaitable response to be matched with Starlette exception handler type hint:

```python
HTTPExceptionHandler = typing.Callable[
    ["Request", Exception], typing.Union["Response", typing.Awaitable["Response"]]
]
```

This PR solved the #693 issue.

### CODE REVIEW

**Comment by agn-7** [comment]
Here's the result after changes:

**Comment by agn-7** [comment]
I don't know what's wrong with this CI? I have no issues with `mypy sqladmin` in my local!

**Comment by aminalaee** [comment]
Thanks for the PR, I will check it soon 👍

**Review by aminalaee — APPROVED** [review]
Thank you for your contribution 👍

**Pull request merged**
