### PR TITLE
Switch icons to FontAwesome 6

### PR DESCRIPTION
**Pull request by EssaAlshammri**

### CODE REVIEW

**Comment by EssaAlshammri** [comment]
@aminalaee should I update the [docs/configurations.md](https://github.com/aminalaee/sqladmin/blob/d03d49553ccc763d4b29eba28e348d81573c12d8/docs/configurations.md?plain=1#L84) to use the new FA6 style syntax ? or are they generated from comments?

**Comment by aminalaee** [comment]
@EssaAlshammri Thank you, yes that makes sense.

**Comment by EssaAlshammri** [comment]
@aminalaee done!

thank you for the great work

**Comment by aminalaee** [comment]
Hey, thanks for the PR,
I'm not sure if you've tested this or not but for me this is not working:
Screenshot 2022-03-08 at 09 48 58

I guess maybe you put the wrong css or the new fontawesome requires the woff files too?

**Comment by EssaAlshammri** [comment]
@EssaAlshammri I will check it out

**Comment by EssaAlshammri** [comment]
@aminalaee it's working now
Screenshot 2022-03-08 185537

**Comment by EssaAlshammri** [comment]
@aminalaee all good now

**Review by aminalaee — APPROVED** [review]
Thanks you for the PR 🎉

**Pull request merged**
