### PR TITLE
Add sqlalchemy_utils PhoneNumberType and ColorType

### PR DESCRIPTION
**Pull request by aminalaee**

### CODE REVIEW

**Comment by lesleslie** [comment]
Any chance of getting ArrowType added to this?

**Comment by aminalaee** [comment]
Yeah sure, I will take a look.

**Comment by aminalaee** [comment]
@lesleslie Looks like it was already supported, I will just add the test to make sure it's working.

**Comment by lesleslie** [comment]
Thank you! I look forward to contributing a few things to this wonderful project in the near future (when I'm done converting my flask/flask-admin app over to fastapi/sqladmin).

**Pull request merged**
