### PR TITLE
ajax.py: get object by PK on form rendering

### PR DESCRIPTION
**Pull request by the-tosh**
Does this workaround fix the issue described in PR https://github.com/aminalaee/sqladmin/pull/727?

### CODE REVIEW

**Review by RXamzin — APPROVED** [review]

**Comment by the-tosh** [comment]
If the solution is good enought, linter recommendations will be added later

**Comment by aminalaee** [comment]
Thanks for the PR, Can you please explain in the issue/PR how you are solving this? I thought this was a new feature TBH, not sure what it is fixing.

**Comment by the-tosh** [comment]
When render a form, relationship field contains string not an object, which leads to the exception discussed in the aforementioned PR (`sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'str'>`)

I suggest to fetch an object from database in such cases (when a string is passed to loader.format() method). What I'm doubt of is all cases I cover with that solution or missing something

**Comment by aminalaee** [comment]
Can you open a new issue with a sample code?
I don't think when rendering a form this error should happen.

**Comment by the-tosh** [comment]
It would be literally the same as in PR #727:

```
...
File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/sqladmin/templates/sqladmin/_macros.html", line 64, in template
    {{ field() }}
  File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/wtforms/fields/core.py", line 176, in __call__
    return self.meta.render_field(self, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/wtforms/meta.py", line 64, in render_field
    return field.widget(field, **render_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/sqladmin/widgets.py", line 57, in __call__
    data = field.loader.format(field.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/sqladmin/ajax.py", line 61, in format
    return {"id": str(get_object_identifier(model)), "text": str(model)}
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/sqladmin/helpers.py", line 181, in get_object_identifier
    primary_keys = get_primary_keys(obj)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/sqladmin/helpers.py", line 176, in get_primary_keys
    return tuple(inspect(model).mapper.primary_key)
                 ^^^^^^^^^^^^^^
  File "/home/tosh/proj/src/venv/lib/python3.12/site-packages/sqlalchemy/inspection.py", line 147, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'str'>
```

So, we could either teach the `loader.format()` method to work with string data or rewrite `field.data` at some point of WTForms workflow (maybe a better solution, but don't see where to do it, though)

**Pull request closed without merging**
