### PR TITLE
Use __class__ when impl is not callable

### PR DESCRIPTION
**Pull request by okapies**
Fixes aminalaee/sqladmin#176.

### CODE REVIEW

**Comment by aminalaee** [comment]
@okapies it's ok. I think it might be missing the testsl coverage now.

**Comment by okapies** [comment]
We cannot test it at the moment because there is no way to configure a custom converter directly (https://github.com/aminalaee/sqladmin/issues/93#issuecomment-1156103788) from outside of `ModelConverterBase`.

**Comment by aminalaee** [comment]
@okapies I have to close this PR and use the other one which also includes the test, I hope you understand this and thank you for the PR.

**Comment by okapies** [comment]
Thanks for the quick fix!

**Pull request closed without merging**
